import cors from "cors"
import express from "express"

const users = [
  {
      id: 1,
      title: "Red dead redemption",
      sub_title: "Red dead Redemption 2",
      genre: "Action", 
      reting: "PEGI 18",
      developer: "Rockstar Games",
      description: "America, 1899. Arthur Morgan e la banda di Van der Linde sono in fuga. Con gli agenti federali e i migliori cacciatori di taglie alle costole, la banda deve rapinare, combattere e rubare per farsi strada e cercare di sopravvivere nel cuore di un'America dura e selvaggia. Una serie di conflitti e divisioni rischiano di mettere a repentaglio l'unità del gruppo, e Arthur si ritrova costretto a scegliere tra i suoi ideali e la lealtà nei confronti della banda che l'ha cresciuto.", 
      price: 29.99,
      discount: 10,
      discount_price: 19.99,
      image_url: "https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png",
      video_url: "https://youtu.be/gmA6MrX81z4",
      platform: "Playstation",
  },
  {
      id: 2,
      title: "Mortal Kombat",
      sub_title: "Mortal Kombat 11 Ultimate",
      genre: "Fighting",
      rating: "PEGI 18",
      developer: "Nether Real Studio",
      description: "Una nuova storia a filmati che contribuirà al proseguimento dell'epica saga che va avanti da ormai 25 anni. I giocatori si caleranno nei panni di svariati personaggi di ieri e di oggi in una narrazione che sfida le leggi dello spazio-tempo mettendo Raiden contro Kronika, Custode del Tempo che ha dato vita a una realtà ambientata nell'alba dei tempi.", 
      price: 44.89,
      discount: 13,
      discount_price: 31.89,
      image_url: "https://gaming-cdn.com/images/products/8432/616x353/mortal-kombat-11-ultimate-ps4-ps5-ultimate-playstation-4-playstation-5-game-playstation-store-europe-cover.jpg?v=1701345153",
      video_url: "https://youtu.be/UoTams2yc0s",
      platform: "Playstation",
  },
  {
      id: 3,
      title: "God of War",
      sub_title: "God of War: Ragnarok",
      genre: "Adventure",
      rating: "PEGI 18",
      developer: "Santa Monica Studio",
      description: "Unisciti a Kratos e Atreus in un viaggio mitico alla ricerca di risposte prima che sopraggiunga il Ragnarök. Insieme, padre e figlio si spingeranno al limite nel corso del loro viaggio in ognuno dei nove regni.", 
      price: 47.99,
      discount: 20,
      discount_price: 27.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
      video_url:"https://youtu.be/ItyO3chi9bo",
      platform: "Playstation",
  },
  {
      id: 4,
      title: "Just dance",
      sub_title: "Just dance 2024 Edition",
      genre: "Multiplayer",
      rating: "PEGI 3",
      developer: "Ubisoft",
      description: "Balla e condividi momenti emozionanti per tutto l'anno con la piattaforma videoludica musicale più amata di tutti i tempi! Just Dance 2024 Edition include 40 brani tra hit recenti e grandi classici, come Flowers di Miley Cyrus, Tití Me Preguntó di Bad Bunny, How You Like That delle BLACKPINK e I Wanna Dance With Somebody di Whitney Houston!", 
      price: 23.99,
      discount: 5,
      discount_price: 18.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202310/0416/5c565008ffe01b5ee17799a0b76f5d1052fcb6aba1adab9e.jpg",
      video_url: "https://youtu.be/NniXc724TtU",
      platform: "Playstation",
  },
  {
      id: 5,
      title: "Horizion",
      sub_title: "Horizon: Forbidden West",
      genre: "Adventure",
      rating: "PEGI 16",
      developer: "Guerrilla Games",
      description: "Unisciti ad Aloy nell'esplorazione dell'Ovest Proibito, una pericolosa frontiera che nasconde nuove e misteriose minacce.", 
      price: 36.42,
      discount: 12,
      discount_price: 24.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202107/3100/cb7gh5N3DjSRathadczu40S9.png",
      video_url: "https://youtu.be/Lq594XmpPBg",
      platform: "Playstation",
  },
  {
      id: 6,
      title: "Medieval Dinasty",
      sub_title: "Medieval Dinasty",
      genre: "FPS",
      rating: "PEGI 16",
      developer: "Render Cube",
      description: "Trova un terreno su cui costruire la tua dimora. Inizierai da semplice agricoltore o cacciatore, ma man mano che acquisirai più esperienza, apprenderai nuove abilità e le affinerai, diventerai il capo di una fiorente cittadina. Progetta, costruisci e migliora la tua casa: trasforma una semplice capanna in una vasta fattoria. Convinci le persone a unirsi al tuo villaggio. Trova il vero amore e metti su famiglia per garantire una continuità nella tua dinastia.", 
      price: 23.99,
      discount: 6,
      discount_price: 17.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202308/1609/9ef2acb3ed2cda2a894342473bd82fda34e73b3a35f57aef.jpg",
      video_url: "https://youtu.be/0m_XJdDvcf4",
      platform: "Playstation",
  },
  {
      id: 7,
      title: "Uncharted",
      sub_title: "Uncharted: Legacy of Thieves",
      genre: "Adventure",
      rating: "PEGI 16",
      developer: "Naughty Dog",
      description: "Scopri le imprese del passato con i ladri Nathan Drake e Chloe Frazer, personaggi tanto carismatici quanto complessi, mentre viaggiano per il mondo in cerca di avventure e storie straordinarie, ora rimasterizzate magistralmente per la console PS5™ con grafica e framerate migliorati.", 
      price: 44.99,
      discount: 6,
      discount_price: 34.89,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202111/2000/gTUWTlvPHzxFJ2JAxtDyI2eS.png",
      video_url: "https://youtu.be/F3Wl-OiZCO4",
      platform: "Playstation",
  },
  {
      id: 8,
      title: "Assassin's creed",
      sub_title: "Assassin's creed: Mirage",
      genre: "Action",
      rating: "PEGI 18",
      developer: "Ubisoft",
      description: "Indossa i panni di Basim, un astuto ladruncolo da strada che cerca risposte e giustizia nelle affollate vie della Bagdad del IX secolo. Grazie a un'antica e misteriosa organizzazione nota come gli Occulti, diventerà un letale Maestro Assassino e cambierà il suo destino in modi imprevedibili.", 
      price: 59.99,
      discount: 20,
      discount_price: 39.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202208/1718/NFf86jgU4AeVYgJBEoEKBpxW.jpg",
      video_url: "https://youtu.be/lirm6x2AJVc",
      platform: "Playstation",
  },
  {
      id: 9,
      title: "FC 24",
      sub_title: "FC 24",
      genre: "sport",
      rating: "PEGI 3",
      developer: "Electronic Arts",
      description: "Un gioco di calcio", 
      price: 33.99,
      discount: 8,
      discount_price: 25.99,
      image_url: "https://cdn1.epicgames.com/offer/4750c68b2bfa4f43933b81cfd5cc510c/EGS_EASPORTSFC24StandardEdition_EACanada_S1_2560x1440-f1772618b782ca975f0bbe33db3a88b3",
      video_url: "https://youtu.be/XhP3Xh4LMA8",
      platform: "Playstation",
  },
  {
      id: 10,
      title: "Ratchet & Clank",
      sub_title: "Ratchet & Clanck: Rift Apart",
      genre: "Adventure",
      rating: "PEGI 3",
      developer: "Imsomniac Games",
      description: "Ratchet e Clank sono tornati! Aiutali a impedire che un imperatore robot riesca a sottomettere i mondi interdimensionali, a partire dal loro universo. Il duo potrà contare sull'aiuto di Rivet, una ribelle Lombax proveniente da un'altra realtà.", 
      price: 35.99,
      discount: 10,
      discount_price: 25.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202101/2921/DwVjpbKOsFOyPdNzmSTSWuxG.png",
      video_url: "https://youtu.be/ai3o0XtrnM8",
      platform: "Playstation",
  },
  {
      id: 11,
      title: "Dragon's Dogma",
      subtitle: "Dragon's Dogma 2",
      genre: "Adventure",
      rating: "PEGI 16",
      developer: "Capcom",
      description: "Dragon's Dogma è una serie di GDR per giocatore singolo ricca di azione e narrazione che offre ai giocatori la possibilità di scrivere la propria storia, dall'aspetto del loro Arisen, la sua classe, la sua squadra, l'approccio alle varie situazioni e molto altro. Ora, in questo attesissimo sequel, il vasto ed esplorabile mondo fantasy di Dragon's Dogma 2 ti attende.", 
      price: 49.99,
      discount: 9,
      discount_price: 40.99,
      image_url: "https://sm.ign.com/ign_it/game/d/dragons-do/dragons-dogma-2_g7t8.jpg",
      video_url: "https://youtu.be/cT0rIgaiPWA",
      platform: "XBOX",
  },
  {
      id: 12,
      title: "Avatar",
      sub_title: "Avatar: Frontiers of Pandora",
      genre: "Adventure",
      rating: "PEGI 12",
      developer: "Ubisoft",
      description: "Avatar: Frontiers of Pandora™ è un gioco d'azione-avventura in prima persona ambientato nell'inesplorata frontiera occidentale di Pandora. Dopo il tuo rapimento e addestramento a opera della corporazione militare umana nota come RDA, hai dimenticato la tua origine na'vi e hai vissuto per servire la sua causa. Quindici anni più tardi hai riconquistato la libertà, ma la tua stessa casa ti risulta straniera. Scopri la tua eredità perduta e cosa significa essere na'vi e lotta al fianco degli altri clan per proteggere Pandora dall'RDA.", 
      price: 34.99,
      discount: 8,
      disocunt_price: 24.99,
      image_url: "https://cdn1.epicgames.com/offer/eca39884bdf14f65af242a8e3ff5b2d9/EGST_StorePortrait_1200x1600_1200x1600-201e8f02dd794c678599d0dcb66d078e",
      video_url: "https://youtu.be/G-1evpoTzWU",
      platform: "XBOX",
  },
  {
      id: 13,
      title: "Halo",
      sub_title: "Halo: Infinite Campaign",
      genre: "FPS",
      rating: "PEGI 16",
      developer: "343 Industries",
      description: "Quando ogni speranza sembra perduta e il destino dell'umanità è appeso a un filo, Master Chief si trova ad affrontare il nemico più spietato di sempre. Indossa la corazza del più grande eroe dell'umanità ed esplora l'Halo in tutta la sua estensione in un'epica avventura open world.", 
      price: 23.99,
      discount: 4,
      discount_price: 19.99,
      image_url: "https://assets.xboxservices.com/assets/34/84/348495df-d8f9-43f4-94cf-12d6e641d610.jpg?n=Halo-Infinite_Poster-Image_1920x1080.jpg",
      video_url: "https://youtu.be/PyMlV5_HRWk",
      platform: "XBOX",
  },
  {
      id: 14,
      title: "Starfield",
      sub_title: "Starfield",
      genre: "FPS",
      rating: "PEGI 16",
      developer: "Bethesda",
      description: "Nell'anno 2330, l'umanità si è avventurata oltre il sistema solare, si è insediata in nuovi pianeti ed è ormai una specie interstellare. In questo contesto ti unirai a Constellation, l'ultimo gruppo di esploratori spaziali alla ricerca di rari manufatti sparsi per la galassia, attraversando enormi distanze nel più grande e ambizioso gioco di Bethesda Game Studios di sempre.", 
      price: 55.89,
      discount: 15,
      discount_price: 40.89,
      image_url: "https://images.everyeye.it/img-cover/starfield-v21-36757-320x450.webp",
      video_url: "https://youtu.be/pYqyVpCV-3c",
      platform: "XBOX",
  },
  {
      id: 15,
      title: "Elden Ring",
      sub_title: "Elden Ring",
      genre: "Action",
      rating: "PEGI 18",
      developer: "FromSoftware",
      description: "Un mondo sconfinato e sorprendente. Un vasto mondo, in cui lande sconfinate e dense di pericoli si intersecano senza soluzione di continuità a dedali sotterranei dalle sontuose architetture tridimensionali. Esplora l'ignoto e combatti minacce mortali in un mondo in cui la sopravvivenza è una conquista.", 
      price: 37.99,
      discount: 4,
      discount_price: 33.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202107/1612/Y5RHNmzAtc6sRYwZlYiKHAxN.png",
      video_url: "https://youtu.be/AKXiKBnzpBQ",
      platform: "XBOX",
  },
  {
      id: 16,
      title: "Dragon Ball Z",
      sub_title: "Dragon Ball Z: Kakarot",
      genre: "Action",
      rating: "PEGI 12",
      developer: "Bandai Namco",
      description: "Ripercorri la storia di Goku e dei guerrieri Z in DRAGON BALL Z: KAKAROT! Oltre rivivere battaglie memorabili, potrai esplorare il mondo di DRAGON BALL Z cacciando, pescando, mangiando e allenandoti con Goku, Gohan, Vegeta e gli altri.", 
      price: 24.99,
      discount: 7,
      discount_price: 17.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202212/1616/ebKSYAneFeVLHD7SAWP1l5TE.png",
      video_url: "https://youtu.be/sixbriRUz9M",
      platform: "XBOX",
  },
  {
      id: 17,
      title: "It takes two",
      sub_title: "It takes two",
      genre: "Indie",
      rating: "PEGI 3",
      developer: "Electronic Arts",
      description: "Parti per la più folle avventura della tua vita con It Takes Two, un'avventura platform che rivoluziona il genere, creata appositamente per il co-op. Invita un amico a giocare gratis con il Pass amici*, collaborate per superare numerose sfide incredibili con un gameplay fuori dagli schemi. Gioca nei panni di Cody e May, una coppia ai ferri corti, due esseri umani che un incantesimo ha trasformato in bambole. Insieme, intrappolati in un mondo fantastico in cui gli imprevisti si celano dietro ogni angolo, dovranno superare ogni sfida per salvare la propria relazione in pericolo.", 
      price: 19.99,
      discount: 10,
      discount_price: 9.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202012/0815/7CRynuLSAb0vysSC4TmZy5e4.png",
      video_url: "https://youtu.be/GAWHzGNcTEw",
      platform: "XBOX",
  },
  {
      id: 18,
      title: "Forza Horizion",
      sub_title: "Forza Horizon 5",
      genre: "Racing",
      rating: "PEGI 3",
      developer: "Playground Games",
      description: "La tua avventura Horizon definitiva ti aspetta! Esplora vivaci paesaggi open world del Messico in continua evoluzione. Divertimento al volante illimitato con centinaia tra le migliori auto al mondo.", 
      price: 50.99,
      discount: 14,
      discount_price: 36.99,
      image_url: "https://cdn.akamai.steamstatic.com/steam/apps/1551360/capsule_616x353.jpg?t=1706912726",
      video_url: "https://youtu.be/FYH9n37B7Yw",
      platform: "XBOX",
  },
  {
      id: 19,
      title: "Like a Dragon: Infinite Wealth",
      sub_title: "Like a Dragon: Infinite Wealth",
      genre: "Fighting",
      rating: "PEGI 18",
      developer: "Ryu ga Gotoku Studio",
      description: "Goditi un combattimento unico nel suo genere con battaglie GDR dinamiche e frenetiche in cui il campo di battaglia stesso diventa la tua arma e non ci sono regole.Adatta le tecniche del tuo gruppo alla situazione da affrontare con lavori e personalizzazioni bizzarri per sopraffare strategicamente i nemici con tecniche sopra le righe.", 
      price: 44.99,
      discount: 15,
      discount_price: 29.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202007/0917/fid2e7IysrUvFqmppIxi48GT.png",
      video_url: "https://youtu.be/ZcYdoEju54c",
      platform: "XBOX",
  },
  {
      id: 20,
      title: "Assassin's creed",
      sub_title: "Assassin's creed: Ezio's Collection",
      genre: "Adventure",
      rating: "PEGI 18",
      developer: "Ubisoft",
      description:"Scrivi la storia nei panni del Maestro Assassino Ezio Auditore da Firenze in questa magnifica collezione che comprende la modalità per giocatore singolo di Assassin's Creed 2, Assassin's Creed Brotherhood, Assassin's Creed Revelations e tutti i DLC con grafica migliorata. Due brevi film, Assassin's Creed Lineage® e Assassin's Creed Embers™, completano l'esperienza di Ezio.", 
      price: 17.99,
      discount: 3,
      discount_price: 14.99,
      image_url: "https://image.api.playstation.com/cdn/EP0001/CUSA04893_00/Du24dEL6C7seAl3UQobFN5QqewZ6EXU5.png",
      video_url: "https://youtu.be/PrlE5PmeasA",
      platform: "XBOX",
  },
  {
      id: 21,
      title: "Disney Dreamlight Valley",
      sub_title: "Disney Dreamlight Valley",
      genre: "Adventure",
      rating: "PEGI 3",
      developer: "Disney",
      description:"Disney Dreamlight Valley è un gioco ibrido che unisce avventura e simulazione sociale, con una miriade di missioni, esplorazioni e attività coinvolgenti al fianco di amici Disney e Pixar vecchi e nuovi. Un tempo, la Dreamlight Valley era un luogo pacifico in cui i personaggi Disney e Pixar vivevano in armonia. Un giorno, però, è giunto l’Oblio, che ha fatto crescere in tutta la valle le Spine della notte e ha fatto svanire gli splendidi ricordi legati a questo luogo magico. Non avendo altri posti in cui andare, i disperati abitanti della Dreamlight Valley si sono rinchiusi nel Castello dei sogni.", 
      price: 39.99,
      discount: 10,
      discount_price: 29.99,
      image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/2x1_NSwitchDS_DisneyDreamlightValley_LionKing_image1600w.jpg",
      video_url: "https://youtu.be/UY5KdtnK4dU",
      platform: "Nintendo",
  },
  {
    id: 22,
    title: "Moonlighter",
    sub_title: "Moonlighter",
    genre: "Indie",
    rating: "PEGI 7",
    developer: "Digital Sun",
    description:"Tanto tempo fa, nel corso di alcuni scavi archeologici, fu portata alla luce una serie di varchi. Ben presto la gente si rese conto che questi antichi varchi conducevano ad altri regni e nuove dimensioni. Vicino al sito archeologico fu fondato un piccolo villaggio dedito al commercio, chiamato Rynoka, che permetteva a coraggiosi e spericolati esploratori di entrare in possesso di tesori inestimabili.", 
    price: 24.99,
    discount: 22,
    discount_price: 2.99,
    image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Moonlighter_image1600w.jpg",
    video_url: "https://youtu.be/Hp7tNAH9Ox0",
    platform: "Nintendo",
},
{
  id: 23,
  title: "Goat Simulator",
  sub_title: "Goat Simulator: The GOATY",
  genre: "Indie",
  rating: "PEGI 12",
  developer: "Coffe stain",
  description:"Come sarà la vita di una capra? Beh, grazie a Goat Simulator adesso puoi avere la risposta a una domanda che ti assillava da sempre! In Goat Simulator vesti i panni di una capra che deve seminare la distruzione più grande possibile. Questo gioco è stato paragonato ai titoli di skateboard vecchia scuola, solo che invece di essere uno skater sei una capra, e invece di eseguire acrobazie fracassi tutto ciò che ti capita a tiro. Facendolo con stile guadagnerai anche più punti!", 
  price: 29.99,
  discount: 25,
  discount_price: 4.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_GoatSimulatorTheGoaty_image1600w.jpg",
  video_url: "https://youtu.be/SRc9jIO1mCI",
  platform: "Nintendo",
},
{
  id: 24,
  title: "Animal Crossing",
  sub_title: "Animal Crossing New Horizon",
  genre: "Multiplayer",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Una vita spensierata è all'orizzonte! Scendi dall'aereo sulla tua personale isola deserta dove nuove amicizie, scoperte e opportunità ti attendono. Crea il tuo paradiso in Animal Crossing: New Horizons per Nintendo Switch!", 
  price: 59.99,
  discount: 20,
  discount_price: 39.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
  video_url: "https://youtu.be/_3YNL0OWio0",
  platform: "Nintendo",
},
{
  id: 25,
  title: "Hogwarts Legacy",
  sub_title: "Hogwarts Legacy",
  genre: "RPG",
  rating: "PEGI 12",
  developer: "Avalanche Software",
  description:"Hogwarts Legacy è un coinvolgente gioco di ruolo d'azione open world, ambientato nel magico universo dei libri di Harry Potter. Ora puoi assumere il controllo della narrazione ed essere il protagonista della tua storia personale nel mondo magico.", 
  price: 59.99,
  discount: 25,
  discount_price: 34.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/2x1_NSwitch_HogwartsLegacy_image1600w.jpg",
  video_url: "https://youtu.be/KOZpJB1FK6Y",
  platform: "Nintendo",
},
{
  id: 26,
  title: "The Elder Scrolls",
  sub_title: "The Elder Scrolls V: Skyrim",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Bethesda",
  description:"Quest'avventura open world dei Bethesda Game Studios® in cui puoi essere chi vuoi e fare ciò che desideri ti permette ora di giocare ovunque: sulla TV di casa o in mobilità. The Elder Scrolls V: Skyrim per Nintendo Switch include funzionalità esclusive, come la possibilità di usare i comandi di movimento per combattere e scassinare serrature, nuovi costumi ed equipaggiamento dalla serie di The Legend of Zelda e la compatibilità con gli amiibo (venduti separatamente).", 
  price: 59.99,
  discount: 30,
  discount_price: 29.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TheElderScrollsVSkyrim_image1600w.jpg",
  video_url: "https://youtu.be/fx0eznPrKpw",
  platform: "Nintendo",
},
{
  id: 27,
  title: "The Survivalist",
  sub_title: "The Survivalist",
  genre: "RPG",
  rating: "PEGI 7",
  developer: "Team17 Digital Ltd",
  description:"Caccia gli animali, a tuo rischio e pericolo, e incontra una serie di creature leggendarie... anche se non tutte potrebbero essere liete di vederti. Ricevi gli incarichi da un misterioso straniero oppure scoprili da solo tra le sabbie dell'isola. Preparati a inoltrarti in uno scenario generato proceduralmente con una varietà estrema di biomi, per un'avventura sempre nuova e diversa a ogni partita.", 
  price: 24.99,
  discount: 22,
  discount_price: 2.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TheSurvivalists_image1600w.jpg",
  video_url: "https://youtu.be/YsEmt5qKvVk",
  platform: "Nintendo",
},
{
  id: 28,
  title: "Football Manager",
  sub_title: "Football Manager 2024 Touch",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "SEGA",
  description:"Scrivi la tua storia. Insegui la gloria immediata alla guida di uno dei principali top club al mondo o sfrutta la nuova compatibilità con i salvataggi precedenti per proseguire il tuo viaggio da FM23 Touch. A te la scelta.", 
  price: 49.99,
  discount: 16,
  discount_price: 33.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/2x1_NSwitchDS_FootballManager2024Touch_image1600w.jpg",
  video_url: "https://youtu.be/YhW8wxAD4H0",
  platform: "Nintendo",
},
{
  id: 29,
  title: "Two Points Hospital",
  sub_title: "Two Points Hospital: Jumbo Edition",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "Two Points Studios",
  description:"Unisciti a oltre 3 milioni di giocatori felici e scopri perché Two Point Hospital è un sano fenomeno! Accresci la tua esperienza di costruttore di ospedali con le quattro enormi espansioni e i due DLC aggiuntivi compresi nella straordinaria Jumbo Edition del gioco, STRABORDANTE DI CONTENUTI!", 
  price: 39.99,
  discount: 34,
  discount_price: 5.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TwoPointHospital_image1600w.jpg",
  video_url: "https://youtu.be/zt7KXD-QPpE",
  platform: "Nintendo",
},
{
  id: 30,
  title: "Doraemon",
  sub_title: "Doraemon Story of Seasons",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "Bandai Namco",
  description:"Dopo essere stati colti di sorpresa da una tempesta, Nobita, il nostro eroe, atterra accidentalmente su un pianeta insieme ai suoi amici. Lì incontrano gli abitanti locali, i quali raccontano che la tempesta ha spazzato via tutto tranne un albero speciale. Nobita e i suoi amici decidono allora di aiutare il villaggio a tornare alla prosperità, in cambio gli abitanti del villaggio aiuteranno loro a far ritorno sulla terra.", 
  price: 49.99,
  discount: 42,
  discount_price: 7.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_DoraemonStoryOfSeasons_image1600w.jpg",
  video_url: "https://youtu.be/YuKO0tUVoQI",
  platform: "Nintendo",
},
{
  id: 31,
  title: "Farming Simulator",
  sub_title: "Farming Simulator 22",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "Coffe Stain",
  description:"Farming Simulator Premium Edition for PC is a farming simulation game in which you can build your own farm to grow an agricultural empire. You can choose everything from the crops you grow to how much automation you want to invest in.", 
  price: 39.99,
  discount: 23,
  discount_price: 26.99,
  image_url: "https://gaming-cdn.com/images/products/14538/616x353/farming-simulator-22-premium-edition-premium-edition-pc-mac-game-steam-cover.jpg?v=1711362759",
  video_url: "https://youtu.be/JpBzfTe_yWE",
  platform: "PC",
},
{
  id: 32,
  title: "Elden Ring",
  sub_title: "Elden Ring: Shadow of the Erdtree",
  genre: "Action",
  rating: "PEGI 18",
  developer: "Bandai Namco",
  description:"Winner of hundreds of accolades including The Game Awards Game of the Year and Golden Joystick Awards Ultimate Game of the Year, ELDEN RING is the acclaimed action RPG epic set in a vast, dark fantasy world.", 
  price: 49.99,
  discount: 11,
  discount_price: 38.99,
  image_url: "https://gaming-cdn.com/images/products/13652/616x353/elden-ring-shadow-of-the-erdtree-pc-game-steam-europe-cover.jpg?v=1709640799",
  video_url: "https://youtu.be/qLZenOn7WUo",
  platform: "PC",
},
{
  id: 33,
  title: "Total War",
  sub_title: "Total War: Pharaoh",
  genre: "Simulation",
  rating: "PEGI 18",
  developer: "SEGA",
  description:"In Total War: PHARAOH immerse yourself in ancient Egypt at the zenith of its power and experience the dramatic events that threaten its destruction. With dynamic real-time battles and incredible turn-based empire management, will you rise to become Egypt's last great Pharaoh, or a conquering Great King of the Hittites? ", 
  price: 39.99,
  discount: 32,
  discount_price: 7.99,
  image_url: "https://gaming-cdn.com/images/products/14196/616x353/total-war-pharaoh-pc-mac-game-steam-cover.jpg?v=1702639864",
  video_url: "https://youtu.be/lLlD650ZBFQ",
  platform: "PC",
},
{
  id: 34,
  title: "Smalland",
  sub_title: "Smalland",
  genre: "Adventure",
  rating: "PEGI 7",
  developer: "Merge Games",
  description:"Traverse lake sized puddles, scale skyscraper sized trees, scramble through cavernous cracks in roads, as you experience a huge open world from a new perspective. Explore dense forests, hazardous swamps and strange ruins left over from the time before. Uncover lore and knowledge from hidden NPCs scattered throughout the world and learn to survive in this vast wilderness.", 
  price: 34.99,
  discount: 16,
  discount_price: 18.99,
  image_url: "https://gaming-cdn.com/images/products/8256/616x353/smalland-survive-the-wilds-pc-game-steam-cover.jpg?v=1708684863",
  video_url: "https://youtu.be/n9EvL-I91TA",
  platform: "PC",
},
{
  id: 35,
  title: "Alone in the dark",
  sub_title: "Alone in the dark",
  genre: "Adventure",
  rating: "PEGI 12",
  developer: "Pieces Interactive",
  description:"We invite you to join us on a journey into madness, where each encounter could be your last. With each step you take closer to unravelling Derceto's mystery, the eyes that watch from the darkness grow hungrier.", 
  price: 59.99,
  discount: 24,
  discount_price: 35.99,
  image_url: "https://gaming-cdn.com/images/products/12675/616x353/alone-in-the-dark-pc-game-steam-europe-cover.jpg?v=1710947479",
  video_url: "https://youtu.be/ddsa1IB9MH4",
  platform: "PC",
},
{
  id: 36,
  title: "RoboCop",
  sub_title: "RoboCop: Rogue City",
  genre: "Action",
  rating: "PEGI 12",
  developer: "Teyon",
  description:"RoboCop: Rogue City for PC is a first-person shooter game that slots in between the events of the films RoboCop 2 and Robocop 3. Anne Lewis returns as RoboCop's partner and is always with you as you play, making a useful sidekick.", 
  price:49.99,
  discount: 30,
  discount_price: 19.99,
  image_url: "https://gaming-cdn.com/images/products/9229/616x353/robocop-rogue-city-pc-game-steam-cover.jpg?v=1701276307",
  video_url: "https://youtu.be/2VS00ILM2TY",
  platform: "PC",
},
{
  id: 37,
  title: "Ghost of Tsushima",
  sub_title: "Ghost of Tsushima: Director's cut",
  genre: "Adventure",
  rating: "PEGI 18",
  developer: "Sucker Punch Production",
  description:"Ghost of Tsushima for PC is an award winning action adventure open world game, with a third-person player perspective. It is set in ancient feudal Japan, but the issues faced by the protagonist will be easily understood by Western, modern players. About", 
  price: 59.99,
  discount: 10,
  discount_price: 49.99,
  image_url: "https://gaming-cdn.com/images/products/9093/616x353/ghost-of-tsushima-director-s-cut-pc-game-steam-cover.jpg?v=1711457077",
  video_url: "https://youtu.be/A5gVt028Hww",
  platform: "PC",
},
{
  id: 38,
  title: "Final Fantasy ",
  sub_title: "Final Fantasy XIV: Dawntrail + Early Access - Europe",
  genre: "RPG",
  rating: "PEGI 12",
  developer: "Square Enix",
  description:"Blue seas, clear skies, and boundless possibilities await in Dawntrail, the newest expansion pack for the critically acclaimed FINAL FANTASY XIV Online! Explore uncharted territories with familiar faces as you discover new tribes, confront formidable threats, and expand your horizons as hope's light dawns once more.", 
  price: 35.99,
  discount: 11,
  discount_price: 24.99,
  image_url: "https://gaming-cdn.com/images/products/15658/616x353/final-fantasy-xiv-dawntrail-early-access-pc-game-europe-cover.jpg?v=1711621232",
  video_url: "https://youtu.be/kgiuQwzB6aU",
  platform: "PC",
},
{
  id: 39,
  title: "Helldivers",
  sub_title: "Helldivers II",
  genre: "FPS",
  rating: "PEGI 18",
  developer: "Arrowhead Game Studio",
  description:"The Galaxy's Last Line of Offence. Enlist in the Helldivers and join the fight for freedom across a hostile galaxy in a fast, frantic, and ferocious third-person shooter. URGENT BROADCAST SUPER EARTH ARMED FORCESFreedom.", 
  price: 39.99,
  discount: 15,
  discount_price: 24.99,
  image_url: "https://gaming-cdn.com/images/products/9575/616x353/helldivers-2-pc-game-steam-europe-cover.jpg?v=1708503564",
  video_url: "https://youtu.be/Dhd9FYLLEPc",
  platform: "PC",
},
{
  id: 40,
  title: "Bound",
  sub_title: "Bound 2",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Ye",
  description:"Bound to fallin' in love", 
  price: 99.99,
  discount: 99.99,
  discount_price: 0,
  image_url: "https://i.pinimg.com/736x/2e/aa/fd/2eaafdcf38154a4fe8bbe41797ee2211.jpg",
  video_url: "https://youtu.be/BBAtAM7vtgc",
  platform: "PC",
},
]


const app = express();
app.use(cors());

app.get('/api/oggetti', (req, res) => {
  res.json(users);
});

const port = 5000;

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});